name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Trigger deployment on Render
      uses: render-examples/deploy-render@v1
      with:
        api_key: ${{ secrets.RENDER_API_KEY }}
        service_id: ${{ secrets.RENDER_SERVICE_ID }}